### ISSUE TITLE
Make a nicer web site for the app

### ISSUE THREAD

**Issue by ffagerho** [TheSoftwareFactory/lokki#9]
http://thesoftwarefactory.github.io/lokki/ is somewhat limited at the moment and should be updated with a bit more info and links to the Google Play store.

**Comment by ffagerho** [comment]
The visual layout is ok, it's just the contents that need to be updated.

**Comment by DarkTan** [comment]
Hi, I am a master student in University of Helsinki, Can I join this course now? I have emailed you, and still waiting for your reply. But I am afraid that you didn't receive email, so I come here and ask you.
Thanks!

**Comment by ffagerho** [comment]
@DarkTan please contact me through my UH CS department email.

**Comment by shresthashiva** [comment]
New template with some more decorated text display. But still need more modification to be add on it .

**Comment by ffagerho** [comment]
What Lokki is? -> What is Lokki?
Don't use word Screens, use Features.
Hide Demo
How To Get It -> Download
Add Developers tab
In the top image carousel, remove the second slide.

What is Lokki and Features are now exactly the same. Either remove Features or come up with something else for What is Lokki.

Get App
Change text to "Lokki is free. New features are being added continuously. Download it here!"
Move source code icon to Developers tab.
Remove the note about iOS and WP8 versions.
Change picture to an android device.

Footer
Add Twitter, Google+ and Facebook pages. Also add GitHub icon and link.

Copyright text:
Copyright © 2015 Lokki Open Source Project contributors
